-- VHDL Entity ece411.PipeMemory.interface
--
-- Created:
--          by - mcasano2.ews (evrt-252-24.ews.illinois.edu)
--          at - 20:44:38 03/28/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY PipeMemory IS
   PORT( 
      CLK         : IN     STD_LOGIC;
      D_ADDRESS   : IN     LC3B_WORD;
      D_DATAOUT   : IN     LC3B_WORD;
      D_MREAD_L   : IN     STD_LOGIC;
      D_MWRITEH_L : IN     STD_LOGIC;
      D_MWRITEL_L : IN     STD_LOGIC;
      I_ADDRESS   : IN     LC3B_WORD;
      I_MREAD_L   : IN     STD_LOGIC;
      RESET_L     : IN     STD_LOGIC;
      D_DATAIN    : OUT    LC3B_WORD;
      D_MRESP_H   : OUT    STD_LOGIC;
      I_DATAIN    : OUT    LC3B_WORD;
      I_MRESP_H   : OUT    STD_LOGIC
   );

-- Declarations

END PipeMemory ;

--
-- VHDL Architecture ece411.PipeMemory.struct
--
-- Created:
--          by - mcasano2.ews (evrt-252-24.ews.illinois.edu)
--          at - 20:44:39 03/28/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;


ARCHITECTURE struct OF PipeMemory IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL D_ADDRESS_pm   : LC3B_WORD;
   SIGNAL D_DATAOUT_pm   : LC3B_OWORD;
   SIGNAL D_MREAD_pm_L   : STD_LOGIC;
   SIGNAL D_MWRITEL_pm_L : STD_LOGIC;
   SIGNAL D_PMDATAIN     : LC3B_OWORD;
   SIGNAL D_PMRESP_H     : STD_LOGIC;
   SIGNAL I_ADDRESS_pm   : LC3B_WORD;
   SIGNAL I_MREAD_pm_L   : STD_LOGIC;
   SIGNAL I_PMDATAIN     : LC3B_OWORD;
   SIGNAL I_PMRESP_H     : STD_LOGIC;


   -- Component Declarations
   COMPONENT DCache
   PORT (
      CLK            : IN     STD_LOGIC ;
      D_ADDRESS      : IN     LC3B_WORD ;
      D_DATAOUT      : IN     LC3B_WORD ;
      D_MREAD_L      : IN     STD_LOGIC ;
      D_MWRITEH_L    : IN     STD_LOGIC ;
      D_MWRITEL_L    : IN     STD_LOGIC ;
      D_PMDATAIN     : IN     LC3B_OWORD ;
      D_PMRESP_H     : IN     STD_LOGIC ;
      RESET_L        : IN     STD_LOGIC ;
      D_ADDRESS_pm   : OUT    LC3B_WORD ;
      D_DATAIN       : OUT    LC3B_WORD ;
      D_DATAOUT_pm   : OUT    LC3B_OWORD ;
      D_MREAD_pm_L   : OUT    STD_LOGIC ;
      D_MRESP_H      : OUT    STD_LOGIC ;
      D_MWRITEL_pm_L : OUT    STD_LOGIC 
   );
   END COMPONENT;
   COMPONENT ICache
   PORT (
      CLK          : IN     STD_LOGIC ;
      I_ADDRESS    : IN     LC3B_WORD ;
      I_MREAD_L    : IN     STD_LOGIC ;
      I_PMDATAIN   : IN     LC3B_OWORD ;
      I_PMRESP_H   : IN     STD_LOGIC ;
      RESET_L      : IN     STD_LOGIC ;
      I_ADDRESS_pm : OUT    LC3B_WORD ;
      I_DATAIN     : OUT    LC3B_WORD ;
      I_MREAD_pm_L : OUT    STD_LOGIC ;
      I_MRESP_H    : OUT    STD_LOGIC 
   );
   END COMPONENT;
   COMPONENT PhysicalMem
   PORT (
      CLK        : IN     STD_LOGIC;
      D_ADDRESS  : IN     LC3B_WORD;
      D_DATAOUT  : IN     LC3B_OWORD;
      D_MREAD_L  : IN     STD_LOGIC;
      D_MWRITE_L : IN     STD_LOGIC;
      I_ADDRESS  : IN     LC3B_WORD;
      I_MREAD_L  : IN     STD_LOGIC;
      RESET_L    : IN     STD_LOGIC;
      D_DATAIN   : OUT    LC3B_OWORD;
      D_MRESP_H  : OUT    STD_LOGIC;
      I_DATAIN   : OUT    LC3B_OWORD;
      I_MRESP_H  : OUT    STD_LOGIC
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : DCache USE ENTITY ece411.DCache;
   FOR ALL : ICache USE ENTITY ece411.ICache;
   FOR ALL : PhysicalMem USE ENTITY ece411.PhysicalMem;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   mdCache : DCache
      PORT MAP (
         CLK            => CLK,
         D_ADDRESS      => D_ADDRESS,
         D_DATAOUT      => D_DATAOUT,
         D_MREAD_L      => D_MREAD_L,
         D_MWRITEH_L    => D_MWRITEH_L,
         D_MWRITEL_L    => D_MWRITEL_L,
         D_PMDATAIN     => D_PMDATAIN,
         D_PMRESP_H     => D_PMRESP_H,
         RESET_L        => RESET_L,
         D_ADDRESS_pm   => D_ADDRESS_pm,
         D_DATAIN       => D_DATAIN,
         D_DATAOUT_pm   => D_DATAOUT_pm,
         D_MREAD_pm_L   => D_MREAD_pm_L,
         D_MRESP_H      => D_MRESP_H,
         D_MWRITEL_pm_L => D_MWRITEL_pm_L
      );
   miCache : ICache
      PORT MAP (
         CLK          => CLK,
         I_ADDRESS    => I_ADDRESS,
         I_MREAD_L    => I_MREAD_L,
         I_PMDATAIN   => I_PMDATAIN,
         I_PMRESP_H   => I_PMRESP_H,
         RESET_L      => RESET_L,
         I_ADDRESS_pm => I_ADDRESS_pm,
         I_DATAIN     => I_DATAIN,
         I_MREAD_pm_L => I_MREAD_pm_L,
         I_MRESP_H    => I_MRESP_H
      );
   mPhyDRAM : PhysicalMem
      PORT MAP (
         RESET_L    => RESET_L,
         CLK        => CLK,
         I_MRESP_H  => I_PMRESP_H,
         I_DATAIN   => I_PMDATAIN,
         D_DATAIN   => D_PMDATAIN,
         D_MRESP_H  => D_PMRESP_H,
         I_MREAD_L  => I_MREAD_pm_L,
         D_MREAD_L  => D_MREAD_pm_L,
         I_ADDRESS  => I_ADDRESS_pm,
         D_ADDRESS  => D_ADDRESS_pm,
         D_MWRITE_L => D_MWRITEL_pm_L,
         D_DATAOUT  => D_DATAOUT_pm
      );

END struct;
